server:
  servlet.context-path: /unleash-demo

spring:
  banner:
    location: classpath:banner.txt
unleash-demo:
  unleash:
    uri: https://unleash.herokuapp.com/api

no.nav.security.jwt.issuer.iss-localhost:
  discoveryurl: http://metadata-selvbetjening
  accepted_audience: aud-localhost
  cookiename: localhost-idtoken
