server:
  servlet.context-path: /unleash-demo

unleash-demo:
  unleash:
    uri: https://unleash.herokuapp.com/api

no.nav.security.jwt.issuer.iss-localhost:
  discoveryurl: http://localhost:${mock-oauth2-server.port}/iss-localhost/.well-known/openid-configuration
  accepted_audience: aud-localhost
  cookiename: localhost-idtoken
